/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Brand Colors - Gamification
        'purple': '#7C3AED',
        'purple-hover': '#8B5CF6',
        'purple-active': '#6D28D9',
        'purple-light': '#A78BFA',
        'purple-dark': '#4C1D95',
        'gold': '#FBBF24',
        'gold-hover': '#FCD34D',
        'gold-accent': '#F59E0B',
        'gold-light': '#FEF3C7',
        'emerald': '#10B981',
        'emerald-hover': '#34D399',
        'emerald-active': '#059669',
        'emerald-light': '#D1FAE5',
        'blue': '#3B82F6',
        'blue-hover': '#60A5FA',
        'blue-active': '#1D4ED8',
        'blue-light': '#DBEAFE',
        'red': '#EF4444',
        'red-hover': '#F87171',
        'red-active': '#DC2626',
        'red-light': '#FEE2E2',
        // Neutral Colors - Backgrounds
        'pure-black': '#000000',
        'dark-gray': '#111827',
        'medium-gray': '#1F2937',
        'light-gray': '#374151',
        // Text Colors
        'pure-white': '#FFFFFF',
        'text-primary': '#FFFFFF',
        'text-secondary': '#E5E7EB',
        'text-tertiary': '#9CA3AF',
        'text-muted': '#6B7280',
        // Legacy support (keeping for backward compatibility)
        'soft-gray': '#374151',
        'muted-gray': '#9CA3AF',
      },
      fontFamily: {
        'heading': ['Playfair Display', 'Georgia', 'Times New Roman', 'serif'],
        'body': ['Roboto', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica Neue', 'Arial', 'sans-serif'],
        'display': ['Playfair Display', 'Georgia', 'Times New Roman', 'serif'],
        'clean': ['Poppins', 'sans-serif'],
        'mono': ['SF Mono', 'Monaco', 'Inconsolata', 'Roboto Mono', 'source-code-pro', 'monospace'],
      },
      fontSize: {
        'hero': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'hero-lg': ['96px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'section': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'section-lg': ['56px', { lineHeight: '1.2', fontWeight: '700' }],
        'feature': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'label': ['18px', { lineHeight: '1.5', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      borderRadius: {
        'none': '0',
        'sm': '0.5rem',
        'DEFAULT': '0.75rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '2.5rem',
        '3xl': '3rem',
        '4xl': '4rem',
        'full': '9999px',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #7C3AED 0%, #6366F1 100%)',
        'gradient-primary-alt': 'linear-gradient(135deg, #7C3AED 0%, #6366F1 100%)',
        'gradient-xp': 'linear-gradient(90deg, #10B981 0%, #059669 100%)',
        'gradient-premium': 'linear-gradient(135deg, #7C3AED 0%, #EC4899 50%, #F43F5E 100%)',
        'gradient-subtle': 'linear-gradient(180deg, rgba(124, 58, 237, 0.5) 0%, transparent 50%, rgba(124, 58, 237, 0.5) 100%)',
        'gradient-sunset': 'linear-gradient(135deg, #7C3AED 0%, #6366F1 100%)',
        'film-grain': `url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)' opacity='0.03'/%3E%3C/svg%3E")`,
      },
      animation: {
        'fade-in': 'fadeIn 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
        'slide-up': 'slideUp 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'glow-gold': 'glowGold 2s ease-in-out infinite alternate',
        'pulse': 'pulse 2s ease-in-out infinite',
        'float': 'float 4s ease-in-out infinite',
        'blob': 'blob 7s infinite',
        'shimmer': 'shimmer 2s infinite',
        'bounce-slow': 'bounce 3s infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'slide-in': 'slideIn 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
        'scale-in': 'scaleIn 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '400': '400ms',
        '500': '500ms',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
        'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(124, 58, 237, 0.3)' },
          '100%': { boxShadow: '0 0 20px rgba(124, 58, 237, 0.6)' },
        },
        glowGold: {
          '0%': { boxShadow: '0 0 5px rgba(251, 191, 36, 0.3)' },
          '100%': { boxShadow: '0 0 20px rgba(251, 191, 36, 0.6)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        shimmer: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        slideIn: {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}

